### ISSUE TITLE
A może tak..

### ISSUE THREAD

**Issue by efik** [PHPers/faq#5]
* Dodać README z info jakie narzędzia tu używać? :octocat: 
* Przerobić pod względem graficznym używając [twbs/bootstrap](https://github.com/twbs/bootstrap) ? :smile:

**Comment by leafnode** [comment]
Ad 1. Tu to znaczy gdzie? Jakie narzędzia?
Ad 2. Po co?

**Comment by efik** [comment]
- Do edycji tego wszystkiego, bo tu widzę jakiś scss. Czy to po prostu z generatora jest szablon? :) 

- ładny design. ( To tylko sugestie )

**Comment by leafnode** [comment]
Ja tylko się dopytuję o motywację :)
Ad. 1 - ok, tylko co chcesz edytować i czemu? Do dodawania punktów wystarczy edycja HTMLa, nie trzeba nic zmieniać w CSSach
Ad. 2 - ten jest brzydki? :)

**Comment by efik** [comment]
Na początek... hmm ... jakieś logo, np słonika po lewej, coś po prawej, tak aby tą pustkę zapełnić. 
Później, kuknę na grupę czy jeszcze się jakieś posty nie powtarzały dosyć często, to uzupełnię.

Nie jest brzydki, taki "inny"
